#!/usr/bin/env bash
set -euo pipefail

SERVER_DIR="$HOME/server"
START_SCRIPT="start.sh"
USER_STOP=false


trap 'USER_STOP=true' SIGINT


if ! cd "$SERVER_DIR" 2>/dev/null; then
  echo "Error: '$SERVER_DIR' not found."
  exit 1
fi


if [[ ! -f "$START_SCRIPT" ]]; then
  echo "Error: 'start.sh' not found."
  exit 1
fi

chmod +x "$START_SCRIPT"


echo " Type 'stop' OR press Ctrl+C to stop"


#watchdog
while true; do
  USER_STOP=false
  echo "Starting Bedrock server..."
  ./start.sh

  EXIT_CODE=$?

  
  if [[ "$USER_STOP" == true ]]; then
    echo
    echo "Server stopped by user"
    break
  fi

  if [[ $EXIT_CODE -eq 0 ]]; then
    echo
    echo "Server stopped by user"
    break
  fi

  # Crash
  echo
  echo "Server crashed (exit code: $EXIT_CODE)."
  echo "Restarting in 5 seconds..."
  sleep 5
done

